export const mockTanks: TankData[] = [
    {
        id: "1",
        name: "T-34",
        model: "Т-34-85",
        image: "/src/assets/tank-1.png",
        type: "Средний танк",
        nation: "СССР",
        tier: 6,
        configuration: "Стандартная",
        battles: 330,
        experience: 752,
        maxBattles: 1000,
    },
    {
        id: "2",
        name: "KV-1",
        model: "КВ-1",
        image: "/src/assets/tank-1.png",
        type: "Тяжёлый танк",
        nation: "СССР",
        tier: 5,
        configuration: "Стандартная",
        battles: 215,
        experience: 543,
        maxBattles: 1000,
    },
    {
        id: "3",
        name: "T-150",
        model: "Т-150",
        image: "/src/assets/tank-1.png",
        type: "Тяжёлый танк",
        nation: "СССР",
        tier: 6,
        configuration: "Стандартная",
        battles: 178,
        experience: 421,
        maxBattles: 1000,
    },
    {
        id: "4",
        name: "IS",
        model: "ИС",
        image: "/src/assets/tank-1.png",
        type: "Тяжёлый танк",
        nation: "СССР",
        tier: 7,
        configuration: "Стандартная",
        battles: 89,
        experience: 287,
        maxBattles: 1000,
    },
    {
        id: "5",
        name: "T-44",
        model: "Т-44",
        image: "/src/assets/tank-1.png",
        type: "Средний танк",
        nation: "СССР",
        tier: 8,
        configuration: "Стандартная",
        battles: 156,
        experience: 634,
        maxBattles: 1000,
    },
    {
        id: "6",
        name: "SU-100",
        model: "СУ-100",
        image: "/src/assets/tank-1.png",
        type: "ПТ-САУ",
        nation: "СССР",
        tier: 6,
        configuration: "Стандартная",
        battles: 267,
        experience: 598,
        maxBattles: 1000,
    },
];
export const strangeLatinText =
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum";
